services:
  app:
    &app
    build:
      context: .
      dockerfile: Dockerfile
      args: 
        APP_USER_ID: ${APP_USER_ID}
    container_name: rails_auth
    volumes:
      - .:/home/auth_app_user/auth_app:cached
      - bundle_cache:/usr/local/bundle
      - ~/.ssh:/home/auth_app_user/.ssh
      - ~/.gnupg:/home/auth_app_user/.gnupg
      - bundle:/bundle
      - rails_cache:/home/auth_app_user/auth_app/tmp/cache
      - ~/.gitconfig:/etc/gitconfig
    tmpfs:
      - /tmp/auth_app
    ports:
      - "3000:3000"
    depends_on:
      rails_auth_db:
        condition: service_healthy
      test_rails_auth_db:
        condition: service_healthy
    env_file:
      - .env
    entrypoint: [ "/home/auth_app_user/auth_app/entrypoint.sh" ]
    command: [ "rails", "server", "-b", "0.0.0.0", "-p", "3000" ]
    stdin_open: true
    tty: true

  rails_auth_db:
    image: postgres:15
    container_name: rails_auth_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - rails_auth_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  test_rails_auth_db:
    image: postgres:15
    container_name: test_rails_auth_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_TEST_DB}
    volumes:
      - test_rails_auth_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_TEST_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  rails_auth_db_data:
  test_rails_auth_db_data:
  rails_auth_tmp:
  bundle_cache:
  bundle:
  rails_cache:
  rails_tmp: