development:
  google:
    google_client_id: <%= ENV['GOOGLE_CLIENT_ID'] %>
    google_client_secret: <%= ENV['GOOGLE_CLIENT_SECRET'] %>
    google_redirect_uri: <%= ENV['GOOGLE_REDIRECT_URI'] %>
    
test:
  google:
    google_client_id: <%= ENV['GOOGLE_CLIENT_ID'] %>
    google_client_secret: <%= ENV['GOOGLE_CLIENT_SECRET'] %>
    google_redirect_uri: <%= ENV['GOOGLE_REDIRECT_URI'] %>

production:
  google:
    google_client_id: <%= ENV['GOOGLE_CLIENT_ID'] %>
    google_client_secret: <%= ENV['GOOGLE_CLIENT_SECRET'] %>
    google_redirect_uri: <%= ENV['GOOGLE_REDIRECT_URI'] %>